#' Plot function for class \code{LDdf}
#' 
#' The function visualises wheter the LD between adjacent values or
#' visualization of pairwise Linkage Disequilibrium (LD) estimates generated by
#' function \code{pairwiseLD} versus marker distance. A single plot is
#' generated for every chromosome.
#' 
#' For more Details see at \code{\link{plotNeighbourLD}} or
#' \code{\link{LDDist}}
#' 
#' @param x Object of class \code{LDdf}, i.e the output of function
#' \code{pairwiseLD} with argument \code{type="data.frame"}.
#' @param gpData Object of class \code{gpData} with object \code{map}
#' @param plotType You can decide, if you like to have a plot with the LD of
#' the neighbouring markers (option \code{"neighbour"}), or you like to have a
#' scatter plot of distance and LD (default option \code{"dist"}).
#' @param dense For \code{plotType="neighbour"}, \code{logical}. Should density
#' visualization for high-density genetic maps be used?
#' @param nMarker For \code{plotType="neighbour"}, \code{logical}. Print number
#' of markers for each chromosome?
#' @param centr For \code{plotType="neighbour"}, \code{numeric} vector.
#' Positions for the centromeres in the same order as chromosomes in
#' \code{map}. If \code{"maize"}, centromere positions of maize in Mbp are
#' used.
#' @param chr For \code{plotType="dist"}, \code{numeric} scalar or vector.
#' Return value is a plot for each chromosome in \code{chr}. Note: Remember to
#' add in a batch-script one empty line for each chromosome, if you use more
#' than one chromosome!
#' @param type For \code{plotType="dist"}, character string to specify the type
#' of plot. Use \code{"p"} for a scatterplot, \code{"bars"} for stacked bars or
#' \code{"nls"} for scatterplot together with nonlinear regression curve
#' according to Hill and Weir (1988).
#' @param breaks For \code{plotType="dist"}, \code{list} containing breaks for
#' stacked bars (optional, only for \code{type="bars"}). Components are
#' \code{dist} with breaks for distance on x-axis and \code{r2} for breaks on
#' for r2 on y-axis. By default, 5 equal spaced categories for dist and r2 are
#' used.
#' @param n For \code{plotType="dist"}, \code{numeric}. Number of observations
#' used to estimate LD. Only required for \code{type="nls"}.
#' @param file Optionally a path to a file where the plot is saved to
#' @param fileFormat \code{character}. At the moment two file formats are
#' supported: pdf and png. Default is \code{"pdf"}.
#' @param onefile \code{logical}. If \code{fileFormat = "pdf"} you can decide,
#' if you like to have all graphics in one file or in multiple files.
#' @param colL The color for the line if \code{type="nls"} is used. In other
#' cases without a meaning.
#' @param colD The color for the dots in the plot of \code{type="nls"} and
#' \code{type="p"}
#' @param \dots further graphical arguments for function \code{plot}
#' @author Hans-Juergen Auinger
#' @seealso \code{\link{plotNeighbourLD}}, \code{\link{LDDist}},
#' \code{\link{plotGenMap}}, \code{\link{pairwiseLD}}
#' @keywords ~kwd1 ~kwd2
#' @export plot.LDdf
#' @importFrom stats dist
#' 
plot.LDdf <- function(x,gpData,plotType="dist",dense=FALSE,nMarker=TRUE,centr=NULL,
                      chr=NULL,type="p",breaks=NULL,n=NULL,file=NULL,fileFormat="pdf",onefile=TRUE,
                      colL=2,colD=1,...){
    if(plotType == "neighbour"){
      plotNeighbourLD(LD=x,gpData=gpData,dense=dense,nMarker=nMarker,centr=centr, file=file, fileFormat=fileFormat,...) 
    } else if(plotType == "dist"){ 
      LDDist(LDdf=x,chr=chr,type=type,breaks=breaks,n=n,file=file,fileFormat=fileFormat,onefile=onefile,colL=colL,colD=colD,...)
    } else stop("plotType has to be whether 'neighbour' or 'dist'!")
}



#' Plot function for class \code{LDmat}
#' 
#' A function to visualize Linkage Disequilibrium estimates between adjacent
#' markers or isualization of pairwise Linkage Disequilibrium (LD) estimates
#' generated by function \code{pairwiseLD} in a LD heatmap for each chromosome
#' using the \code{LDheatmap} package (Shin et al, 2006) .
#' 
#' For more details see at \code{\link{plotNeighbourLD}} or \code{\link{LDMap}}
#' 
#' @param x Object of class \code{LDmat}, i.e the output of function
#' \code{pairwiseLD} with argument \code{type="matrix"}.
#' @param gpData Object of class \code{gpData} with object \code{map}
#' @param plotType You can decide, if you like to have a plot with the LD of
#' the neighbouring markers (option \code{"neighbour"}), or you like to have a
#' heatmap of the LD (default option \code{"map"}).
#' @param dense For \code{plotType="neighbour"}, \code{logical}. Should density
#' visualization for high-density genetic maps be used?
#' @param nMarker For \code{plotType="neighbour"}, \code{logical}. Print number
#' of markers for each chromosome?
#' @param centr For \code{plotType="neighbour"}, \code{numeric} vector.
#' Positions for the centromeres in the same order as chromosomes in
#' \code{map}. If \code{"maize"}, centromere positions of maize in Mbp are
#' used.
#' @param chr For \code{plotType="map"}, \code{numeric} scalar or vector.
#' Return value is a plot for each chromosome in \code{chr}. Note: Remember to
#' add in a batch-script one empty line for each chromosome, if you use more
#' than one chromosome!
#' @param file Optionally a path to a file where the plot is saved to
#' @param fileFormat \code{character}. At the moment two file formats are
#' supported: pdf and png. Default is \code{"pdf"}.
#' @param onefile \code{logical}. If \code{fileFormat = "pdf"} you can decide,
#' if you like to have all graphics in one file or in multiple files.
#' @param \dots Further arguments that could be passed to function
#' \code{LDheatmap}
#' @author Hans-Juergen Auinger
#' @seealso \code{\link{plotNeighbourLD}}, \code{\link{LDDist}},
#' \code{\link{plotGenMap}}, \code{\link{pairwiseLD}}
#' @keywords ~kwd1 ~kwd2
#' @export plot.LDmat
plot.LDmat <- function(x,gpData,plotType="map",dense=FALSE,nMarker=TRUE,centr=NULL,
                       chr=NULL,file=NULL,fileFormat="pdf",onefile=TRUE,...){
    if(plotType == "neighbour"){
      plotNeighbourLD(LD=x,gpData=gpData,dense=dense,nMarker=nMarker,centr=centr,file=file,fileFormat=fileFormat,...)
    } else if(plotType == "map"){
      LDMap(LDmat=x,gpData=gpData,chr=chr,file=file,fileFormat=fileFormat,onefile=onefile,...)
    } else stop("plotType has to be whether 'neighbour' or 'map'!")
}
